# Generated by Django 5.0.3 on 2024-03-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dataitem_delete_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataItem',
            new_name='Insight',
        ),
    ]
