# Generated by Django 5.0.3 on 2024-03-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_dataitem_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='added',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insight',
            name='insight',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='intensity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='likelihood',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='pestle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insight',
            name='published',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insight',
            name='relevance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insight',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insight',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='insight',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insight',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
