# Generated by Django 5.0.3 on 2024-03-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_insight_added_alter_insight_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='insight',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='intensity',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='likelihood',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='relevance',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
